### ISSUE TITLE
OPENGL_GPU_INTEROP

### ISSUE THREAD

**Issue by gialen** [stereolabs/zed-oculus#3]
How can I add the preprocessor definition OPENGL_GPU_INTEROP?

**Comment by Hokbras** [comment]
Hi,

There are several solutions. The best solution is to add this line in the CMakeLists.txt file:

```
add_definitions(-DOPENGL_GPU_INTEROP)
```

The simplest but not the cleanest solution is to add this line before the line [39](https://github.com/stereolabs/zed-oculus/blob/master/src/main.cpp#L39) in the main.cpp file:

```
#define OPENGL_GPU_INTEROP 1
```

I hope this answer your question. :)
