### ISSUE TITLE
Getting black images when using this tutorial with Oculus Rift

### ISSUE THREAD

**Issue by rkachach** [stereolabs/zed-oculus#4]
I'm trying to use this tutorial with the following setup:
- Oculus Rift + Zed mini
- Windows 10
- Cuda v9.1
- ZED SDK 2.3.3 (my zed mini camera doesn't work with the SDK 2.2)
- SDL 2.0.8
- Oculus SDK: 1.17.0

I'm able to build the setup and launch the program, however I just get black window. I have tested separately the Zed mini (using the explorer) and it's working correctly in 720 and 60fps. In addtion I'm able to see that the images area being read from the camera. So It seems that something is going wrong while trying to display these images using Cuda/OpenGL. 

Following is a screen capture of the current output:
![imagen](https://user-images.githubusercontent.com/15921511/38740402-bfb5c4b0-3f37-11e8-8b81-80b31d28cfbe.png)

Please, could you take a look? any help is more thank welcome.

**Comment by WASCHMASCHINE** [comment]
Hey redobot,

the last update was 5 months ago for SDK 2.2. Just a hint. You can find archived versions of the SDK online.

**Comment by rkachach** [comment]
Unfrotunately my Zed camera doesn't work with the SDK 2.2, it seems to only work with the latest SDK 2.3. So going back to the SD 2.2 is not an option in this case :(

**Comment by rkachach** [comment]
This issue was caused by the software setup of the machine that I was using. I'm not sure exactly of the root cause but I'm able to run the demo successfully in other machines. So I'm closing this issue.

**Comment by rkachach** [comment]
This issue is a little bit old, but finally we realized the root cause. Basically if you run the demo in a PC with

**Comment by rkachach** [comment]
Finally we figured out what's the root cause of this issue. Basically when the machine has more than one GPU the demo doesn't work because the ZED mini is using a different  GPU than the one used for rendering. As consequence when you copy the textures you get a black image because you are using a different GPU. To solve the issue we just force the GPU to be used by the ZED camera as  following:

  
```
  int num_cuda;
  cudaGetDeviceCount(&num_cuda);

  sl::InitParameters init_parameters;
  init_parameters.depth_mode = sl::DEPTH_MODE_PERFORMANCE;
  init_parameters.camera_resolution = sl::RESOLUTION_HD720;
  init_parameters.camera_fps = 60;
  init_parameters.coordinate_units = sl::UNIT_MILLIMETER;
  init_parameters.depth_minimum_distance = 300; 
  init_parameters.sdk_gpu_id = num_cuda-1; //Force the GPU used by the ZED camera

```
