### ISSUE TITLE
Update to Oculus Quest 2

### ISSUE THREAD

**Issue by Russ76** [stereolabs/zed-oculus#8]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues.
- [X] This issue is not a question, bug report, or anything other than a feature request directly related to this project.

### Proposal

Since Oculus Quest 2 has a larger resolution, this package would work even better with it. Where does one adjust the code for the 1832 x 1080 size image? Or could this read from a configuration file in order to set its image size? Perhaps a file that listed the different models of VR headsets. The configuration file could also adjust the HIT value as desired.

### Use-Case

Attempting to use this to send images to VR headset to "see" as the robot is seeing, in near real time, without extra packages such as Unity, Steam, etc.

**Comment by keli95566** [comment]
Hi @Russ76, I am working on the same ideas here. Would you mind sharing any updates/solutions you have found?

**Comment by Russ76** [comment]
I have system set up now with outdoor robot and EAP streaming ZED video to laptop. It is Jetson TX1 and an Acer laptop with Nvidia GPU. Performance is very good, near real time. 720P. It have not gotten video stream into Oculus yet. I want to use head movement to transfer to robot camera pan/tilt in final version. Now pan/tilt is with hand controller.

**Comment by Russ76** [comment]
@keli95566, Any update with your work with Zed?
